apiVersion: v1
entries:
  jx-pipelines-visualizer:
  - apiVersion: v1
    appVersion: 0.0.0
    created: "2020-09-18T12:26:09.458566232Z"
    description: Web UI for Jenkins X, with a clear goal - visualize the pipelines
      - and their logs.
    digest: b99f11c733f820b11846f47faa8e70e2f342d0c09701c05c8056b579581db9b8
    home: https://github.com/dailymotion/jx-pipelines-visualizer
    name: jx-pipelines-visualizer
    sources:
    - https://github.com/dailymotion/jx-pipelines-visualizer
    urls:
    - https://github.com/dailymotion/jx-pipelines-visualizer/releases/download/jx-pipelines-visualizer-0.0.0/jx-pipelines-visualizer-0.0.0.tgz
    version: 0.0.0
generated: "2020-09-18T12:26:09.350192161Z"
